/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PasatiemposRouteImport } from './routes/pasatiempos'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as GastronomiaRouteImport } from './routes/gastronomia'
import { Route as EntrevistasRouteImport } from './routes/entrevistas'
import { Route as EntretenimientoRouteImport } from './routes/entretenimiento'
import { Route as ConspiracionRouteImport } from './routes/conspiracion'
import { Route as ActualidadRouteImport } from './routes/actualidad'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiSubscribeRouteImport } from './routes/api/subscribe'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminNewspaperRouteImport } from './routes/admin.newspaper'
import { Route as AdminNewRouteImport } from './routes/admin.new'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as RevistaNumberIndexRouteImport } from './routes/revista.$number.index'
import { Route as AdminPostsIndexRouteImport } from './routes/admin.posts.index'
import { Route as RevistaNumberLeerRouteImport } from './routes/revista.$number.leer'
import { Route as NoticiaSectionSlugRouteImport } from './routes/noticia.$section.$slug'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiAdminNotifyIssueRouteImport } from './routes/api/admin.notify-issue'
import { Route as AdminPostsNewRouteImport } from './routes/admin.posts.new'
import { Route as AdminIdEditRouteImport } from './routes/admin.$id.edit'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AdminPostsIdEditRouteImport } from './routes/admin.posts.$id.edit'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PasatiemposRoute = PasatiemposRouteImport.update({
  id: '/pasatiempos',
  path: '/pasatiempos',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const GastronomiaRoute = GastronomiaRouteImport.update({
  id: '/gastronomia',
  path: '/gastronomia',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrevistasRoute = EntrevistasRouteImport.update({
  id: '/entrevistas',
  path: '/entrevistas',
  getParentRoute: () => rootRouteImport,
} as any)
const EntretenimientoRoute = EntretenimientoRouteImport.update({
  id: '/entretenimiento',
  path: '/entretenimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const ConspiracionRoute = ConspiracionRouteImport.update({
  id: '/conspiracion',
  path: '/conspiracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualidadRoute = ActualidadRouteImport.update({
  id: '/actualidad',
  path: '/actualidad',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscribeRoute = ApiSubscribeRouteImport.update({
  id: '/api/subscribe',
  path: '/api/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/admin/subscribers',
  path: '/admin/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewspaperRoute = AdminNewspaperRouteImport.update({
  id: '/admin/newspaper',
  path: '/admin/newspaper',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/admin/new',
  path: '/admin/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RevistaNumberIndexRoute = RevistaNumberIndexRouteImport.update({
  id: '/revista/$number/',
  path: '/revista/$number/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/admin/posts/',
  path: '/admin/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const RevistaNumberLeerRoute = RevistaNumberLeerRouteImport.update({
  id: '/revista/$number/leer',
  path: '/revista/$number/leer',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiaSectionSlugRoute = NoticiaSectionSlugRouteImport.update({
  id: '/noticia/$section/$slug',
  path: '/noticia/$section/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminNotifyIssueRoute = ApiAdminNotifyIssueRouteImport.update({
  id: '/api/admin/notify-issue',
  path: '/api/admin/notify-issue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/admin/posts/new',
  path: '/admin/posts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIdEditRoute = AdminIdEditRouteImport.update({
  id: '/admin/$id/edit',
  path: '/admin/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsIdEditRoute = AdminPostsIdEditRouteImport.update({
  id: '/admin/posts/$id/edit',
  path: '/admin/posts/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualidad': typeof ActualidadRoute
  '/conspiracion': typeof ConspiracionRoute
  '/entretenimiento': typeof EntretenimientoRoute
  '/entrevistas': typeof EntrevistasRoute
  '/gastronomia': typeof GastronomiaRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pasatiempos': typeof PasatiemposRoute
  '/profile': typeof ProfileRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/newspaper': typeof AdminNewspaperRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/$id/edit': typeof AdminIdEditRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/api/admin/notify-issue': typeof ApiAdminNotifyIssueRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/noticia/$section/$slug': typeof NoticiaSectionSlugRoute
  '/revista/$number/leer': typeof RevistaNumberLeerRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/revista/$number/': typeof RevistaNumberIndexRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualidad': typeof ActualidadRoute
  '/conspiracion': typeof ConspiracionRoute
  '/entretenimiento': typeof EntretenimientoRoute
  '/entrevistas': typeof EntrevistasRoute
  '/gastronomia': typeof GastronomiaRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pasatiempos': typeof PasatiemposRoute
  '/profile': typeof ProfileRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/newspaper': typeof AdminNewspaperRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin': typeof AdminIndexRoute
  '/admin/$id/edit': typeof AdminIdEditRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/api/admin/notify-issue': typeof ApiAdminNotifyIssueRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/noticia/$section/$slug': typeof NoticiaSectionSlugRoute
  '/revista/$number/leer': typeof RevistaNumberLeerRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/revista/$number': typeof RevistaNumberIndexRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualidad': typeof ActualidadRoute
  '/conspiracion': typeof ConspiracionRoute
  '/entretenimiento': typeof EntretenimientoRoute
  '/entrevistas': typeof EntrevistasRoute
  '/gastronomia': typeof GastronomiaRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pasatiempos': typeof PasatiemposRoute
  '/profile': typeof ProfileRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/newspaper': typeof AdminNewspaperRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/$id/edit': typeof AdminIdEditRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/api/admin/notify-issue': typeof ApiAdminNotifyIssueRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/noticia/$section/$slug': typeof NoticiaSectionSlugRoute
  '/revista/$number/leer': typeof RevistaNumberLeerRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/revista/$number/': typeof RevistaNumberIndexRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualidad'
    | '/conspiracion'
    | '/entretenimiento'
    | '/entrevistas'
    | '/gastronomia'
    | '/llms.txt'
    | '/pasatiempos'
    | '/profile'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/admin/login'
    | '/admin/new'
    | '/admin/newspaper'
    | '/admin/subscribers'
    | '/admin/users'
    | '/api/subscribe'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/admin/'
    | '/admin/$id/edit'
    | '/admin/posts/new'
    | '/api/admin/notify-issue'
    | '/lovable/email/suppression'
    | '/noticia/$section/$slug'
    | '/revista/$number/leer'
    | '/admin/posts/'
    | '/revista/$number/'
    | '/admin/posts/$id/edit'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualidad'
    | '/conspiracion'
    | '/entretenimiento'
    | '/entrevistas'
    | '/gastronomia'
    | '/llms.txt'
    | '/pasatiempos'
    | '/profile'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/admin/login'
    | '/admin/new'
    | '/admin/newspaper'
    | '/admin/subscribers'
    | '/admin/users'
    | '/api/subscribe'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/admin'
    | '/admin/$id/edit'
    | '/admin/posts/new'
    | '/api/admin/notify-issue'
    | '/lovable/email/suppression'
    | '/noticia/$section/$slug'
    | '/revista/$number/leer'
    | '/admin/posts'
    | '/revista/$number'
    | '/admin/posts/$id/edit'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/actualidad'
    | '/conspiracion'
    | '/entretenimiento'
    | '/entrevistas'
    | '/gastronomia'
    | '/llms.txt'
    | '/pasatiempos'
    | '/profile'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/admin/login'
    | '/admin/new'
    | '/admin/newspaper'
    | '/admin/subscribers'
    | '/admin/users'
    | '/api/subscribe'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/admin/'
    | '/admin/$id/edit'
    | '/admin/posts/new'
    | '/api/admin/notify-issue'
    | '/lovable/email/suppression'
    | '/noticia/$section/$slug'
    | '/revista/$number/leer'
    | '/admin/posts/'
    | '/revista/$number/'
    | '/admin/posts/$id/edit'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualidadRoute: typeof ActualidadRoute
  ConspiracionRoute: typeof ConspiracionRoute
  EntretenimientoRoute: typeof EntretenimientoRoute
  EntrevistasRoute: typeof EntrevistasRoute
  GastronomiaRoute: typeof GastronomiaRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PasatiemposRoute: typeof PasatiemposRoute
  ProfileRoute: typeof ProfileRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewRoute: typeof AdminNewRoute
  AdminNewspaperRoute: typeof AdminNewspaperRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiSubscribeRoute: typeof ApiSubscribeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminIdEditRoute: typeof AdminIdEditRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  ApiAdminNotifyIssueRoute: typeof ApiAdminNotifyIssueRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  NoticiaSectionSlugRoute: typeof NoticiaSectionSlugRoute
  RevistaNumberLeerRoute: typeof RevistaNumberLeerRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  RevistaNumberIndexRoute: typeof RevistaNumberIndexRoute
  AdminPostsIdEditRoute: typeof AdminPostsIdEditRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pasatiempos': {
      id: '/pasatiempos'
      path: '/pasatiempos'
      fullPath: '/pasatiempos'
      preLoaderRoute: typeof PasatiemposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastronomia': {
      id: '/gastronomia'
      path: '/gastronomia'
      fullPath: '/gastronomia'
      preLoaderRoute: typeof GastronomiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrevistas': {
      id: '/entrevistas'
      path: '/entrevistas'
      fullPath: '/entrevistas'
      preLoaderRoute: typeof EntrevistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entretenimiento': {
      id: '/entretenimiento'
      path: '/entretenimiento'
      fullPath: '/entretenimiento'
      preLoaderRoute: typeof EntretenimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conspiracion': {
      id: '/conspiracion'
      path: '/conspiracion'
      fullPath: '/conspiracion'
      preLoaderRoute: typeof ConspiracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualidad': {
      id: '/actualidad'
      path: '/actualidad'
      fullPath: '/actualidad'
      preLoaderRoute: typeof ActualidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscribe': {
      id: '/api/subscribe'
      path: '/api/subscribe'
      fullPath: '/api/subscribe'
      preLoaderRoute: typeof ApiSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/admin/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/newspaper': {
      id: '/admin/newspaper'
      path: '/admin/newspaper'
      fullPath: '/admin/newspaper'
      preLoaderRoute: typeof AdminNewspaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/admin/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revista/$number/': {
      id: '/revista/$number/'
      path: '/revista/$number'
      fullPath: '/revista/$number/'
      preLoaderRoute: typeof RevistaNumberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/admin/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revista/$number/leer': {
      id: '/revista/$number/leer'
      path: '/revista/$number/leer'
      fullPath: '/revista/$number/leer'
      preLoaderRoute: typeof RevistaNumberLeerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticia/$section/$slug': {
      id: '/noticia/$section/$slug'
      path: '/noticia/$section/$slug'
      fullPath: '/noticia/$section/$slug'
      preLoaderRoute: typeof NoticiaSectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/notify-issue': {
      id: '/api/admin/notify-issue'
      path: '/api/admin/notify-issue'
      fullPath: '/api/admin/notify-issue'
      preLoaderRoute: typeof ApiAdminNotifyIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/admin/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$id/edit': {
      id: '/admin/$id/edit'
      path: '/admin/$id/edit'
      fullPath: '/admin/$id/edit'
      preLoaderRoute: typeof AdminIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/$id/edit': {
      id: '/admin/posts/$id/edit'
      path: '/admin/posts/$id/edit'
      fullPath: '/admin/posts/$id/edit'
      preLoaderRoute: typeof AdminPostsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualidadRoute: ActualidadRoute,
  ConspiracionRoute: ConspiracionRoute,
  EntretenimientoRoute: EntretenimientoRoute,
  EntrevistasRoute: EntrevistasRoute,
  GastronomiaRoute: GastronomiaRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PasatiemposRoute: PasatiemposRoute,
  ProfileRoute: ProfileRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNewRoute: AdminNewRoute,
  AdminNewspaperRoute: AdminNewspaperRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiSubscribeRoute: ApiSubscribeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminIdEditRoute: AdminIdEditRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
  ApiAdminNotifyIssueRoute: ApiAdminNotifyIssueRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  NoticiaSectionSlugRoute: NoticiaSectionSlugRoute,
  RevistaNumberLeerRoute: RevistaNumberLeerRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  RevistaNumberIndexRoute: RevistaNumberIndexRoute,
  AdminPostsIdEditRoute: AdminPostsIdEditRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
